package com.mycompany.calculator;

import java.util.Scanner;
import javax.swing.JMenu;
import javax.swing.JOptionPane;

public class calculator_gui extends javax.swing.JFrame {

    private double firstNumber, result, principleAmount, rate, timeSpan, temp;
    private int calculations, currentType, desiredType;
    
    Scanner scnr = new Scanner (System.in);
    
    
    
    public calculator_gui() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        blankBttn = new javax.swing.JButton();
        textFeild = new javax.swing.JTextField();
        numberTwo = new javax.swing.JButton();
        squareRoot = new javax.swing.JButton();
        numberEight = new javax.swing.JButton();
        numberNine = new javax.swing.JButton();
        numberOne = new javax.swing.JButton();
        numberFour = new javax.swing.JButton();
        numberFive = new javax.swing.JButton();
        numberSix = new javax.swing.JButton();
        additionSign = new javax.swing.JButton();
        numberThree = new javax.swing.JButton();
        numberZero = new javax.swing.JButton();
        numberSeven = new javax.swing.JButton();
        periodSign = new javax.swing.JButton();
        equalsSign = new javax.swing.JButton();
        multiplicationSign = new javax.swing.JButton();
        subtractionSign = new javax.swing.JButton();
        divisionSign = new javax.swing.JButton();
        backSpace = new javax.swing.JButton();
        clearText1 = new javax.swing.JButton();
        previousNumber = new javax.swing.JTextField();
        menuBar = new javax.swing.JMenuBar();
        mainMenu = new javax.swing.JMenu();
        interestMenu = new javax.swing.JMenu();
        simpleInterest = new javax.swing.JMenuItem();
        compoundInterest = new javax.swing.JMenuItem();
        profitMenu = new javax.swing.JMenu();
        profitCalculation = new javax.swing.JMenuItem();
        lossCalculation = new javax.swing.JMenuItem();
        tempMenu = new javax.swing.JMenu();
        jMenu2 = new javax.swing.JMenu();
        celsiusToFahrenheit = new javax.swing.JMenuItem();
        celsiusToKelvin = new javax.swing.JMenuItem();
        jMenu1 = new javax.swing.JMenu();
        fahrenToCelsius = new javax.swing.JMenuItem();
        fahrenToKelvin = new javax.swing.JMenuItem();
        kelvinToCelsius = new javax.swing.JMenu();
        jMenuItem3 = new javax.swing.JMenuItem();
        kelvinToFahren = new javax.swing.JMenuItem();
        blankMenuOption = new javax.swing.JMenu();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("CALCULATOR");
        setBackground(new java.awt.Color(0, 0, 0));
        setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        setForeground(new java.awt.Color(0, 0, 0));
        setName("calculator"); // NOI18N
        setType(java.awt.Window.Type.UTILITY);

        blankBttn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                blankBttnActionPerformed(evt);
            }
        });

        textFeild.setFont(new java.awt.Font("Microsoft Tai Le", 1, 18)); // NOI18N
        textFeild.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        textFeild.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                textFeildActionPerformed(evt);
            }
        });

        numberTwo.setBackground(new java.awt.Color(0, 0, 0));
        numberTwo.setFont(new java.awt.Font("Microsoft Tai Le", 1, 18)); // NOI18N
        numberTwo.setForeground(new java.awt.Color(255, 255, 255));
        numberTwo.setText("2");
        numberTwo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                numberTwoActionPerformed(evt);
            }
        });

        squareRoot.setFont(new java.awt.Font("sansserif", 0, 18)); // NOI18N
        squareRoot.setText("^2");
        squareRoot.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                squareRootActionPerformed(evt);
            }
        });

        numberEight.setBackground(new java.awt.Color(0, 0, 0));
        numberEight.setFont(new java.awt.Font("Microsoft Tai Le", 1, 18)); // NOI18N
        numberEight.setForeground(new java.awt.Color(255, 255, 255));
        numberEight.setText("8");
        numberEight.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                numberEightActionPerformed(evt);
            }
        });

        numberNine.setBackground(new java.awt.Color(0, 0, 0));
        numberNine.setFont(new java.awt.Font("Microsoft Tai Le", 1, 18)); // NOI18N
        numberNine.setForeground(new java.awt.Color(255, 255, 255));
        numberNine.setText("9");
        numberNine.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                numberNineActionPerformed(evt);
            }
        });

        numberOne.setBackground(new java.awt.Color(0, 0, 0));
        numberOne.setFont(new java.awt.Font("Microsoft Tai Le", 1, 18)); // NOI18N
        numberOne.setForeground(new java.awt.Color(255, 255, 255));
        numberOne.setText("1");
        numberOne.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                numberOneActionPerformed(evt);
            }
        });

        numberFour.setBackground(new java.awt.Color(0, 0, 0));
        numberFour.setFont(new java.awt.Font("Microsoft Tai Le", 1, 18)); // NOI18N
        numberFour.setForeground(new java.awt.Color(255, 255, 255));
        numberFour.setText("4");
        numberFour.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                numberFourActionPerformed(evt);
            }
        });

        numberFive.setBackground(new java.awt.Color(0, 0, 0));
        numberFive.setFont(new java.awt.Font("Microsoft Tai Le", 1, 18)); // NOI18N
        numberFive.setForeground(new java.awt.Color(255, 255, 255));
        numberFive.setText("5");
        numberFive.setAutoscrolls(true);
        numberFive.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                numberFiveActionPerformed(evt);
            }
        });

        numberSix.setBackground(new java.awt.Color(0, 0, 0));
        numberSix.setFont(new java.awt.Font("Microsoft Tai Le", 1, 18)); // NOI18N
        numberSix.setForeground(new java.awt.Color(255, 255, 255));
        numberSix.setText("6");
        numberSix.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                numberSixActionPerformed(evt);
            }
        });

        additionSign.setText("+");
        additionSign.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                additionSignActionPerformed(evt);
            }
        });

        numberThree.setBackground(new java.awt.Color(0, 0, 0));
        numberThree.setFont(new java.awt.Font("Microsoft Tai Le", 1, 18)); // NOI18N
        numberThree.setForeground(new java.awt.Color(255, 255, 255));
        numberThree.setText("3");
        numberThree.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                numberThreeActionPerformed(evt);
            }
        });

        numberZero.setBackground(new java.awt.Color(0, 0, 0));
        numberZero.setFont(new java.awt.Font("Microsoft Tai Le", 1, 18)); // NOI18N
        numberZero.setForeground(new java.awt.Color(255, 255, 255));
        numberZero.setText("0");
        numberZero.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                numberZeroActionPerformed(evt);
            }
        });

        numberSeven.setBackground(new java.awt.Color(0, 0, 0));
        numberSeven.setFont(new java.awt.Font("Microsoft Tai Le", 1, 18)); // NOI18N
        numberSeven.setForeground(new java.awt.Color(255, 255, 255));
        numberSeven.setText("7");
        numberSeven.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                numberSevenActionPerformed(evt);
            }
        });

        periodSign.setBackground(new java.awt.Color(0, 0, 0));
        periodSign.setFont(new java.awt.Font("Microsoft Tai Le", 1, 18)); // NOI18N
        periodSign.setForeground(new java.awt.Color(255, 255, 255));
        periodSign.setText(".");

        equalsSign.setBackground(new java.awt.Color(0, 0, 0));
        equalsSign.setFont(new java.awt.Font("Microsoft Tai Le", 1, 24)); // NOI18N
        equalsSign.setForeground(new java.awt.Color(255, 255, 255));
        equalsSign.setText("=");
        equalsSign.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                equalsSignActionPerformed(evt);
            }
        });

        multiplicationSign.setText("*");
        multiplicationSign.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                multiplicationSignActionPerformed(evt);
            }
        });

        subtractionSign.setText("-");
        subtractionSign.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                subtractionSignActionPerformed(evt);
            }
        });

        divisionSign.setText("/");
        divisionSign.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                divisionSignActionPerformed(evt);
            }
        });

        backSpace.setFont(new java.awt.Font("sansserif", 0, 14)); // NOI18N
        backSpace.setText("BS");
        backSpace.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backSpaceActionPerformed(evt);
            }
        });

        clearText1.setFont(new java.awt.Font("Microsoft Tai Le", 1, 18)); // NOI18N
        clearText1.setText("C");
        clearText1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                clearText1ActionPerformed(evt);
            }
        });

        previousNumber.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                previousNumberActionPerformed(evt);
            }
        });

        mainMenu.setText("Menu");

        interestMenu.setText("Interest");

        simpleInterest.setFont(new java.awt.Font("Microsoft Tai Le", 1, 10)); // NOI18N
        simpleInterest.setText("Simple");
        simpleInterest.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        simpleInterest.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                simpleInterestActionPerformed(evt);
            }
        });
        interestMenu.add(simpleInterest);

        compoundInterest.setText("Compund");
        interestMenu.add(compoundInterest);

        mainMenu.add(interestMenu);

        profitMenu.setText("Profit");

        profitCalculation.setText("Profit");
        profitMenu.add(profitCalculation);

        lossCalculation.setText("Loss");
        profitMenu.add(lossCalculation);

        mainMenu.add(profitMenu);

        tempMenu.setText("Temperature");

        jMenu2.setText("Celsius");

        celsiusToFahrenheit.setText("Fahrenheit");
        celsiusToFahrenheit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                celsiusToFahrenheitActionPerformed(evt);
            }
        });
        jMenu2.add(celsiusToFahrenheit);

        celsiusToKelvin.setText("Kelvin");
        jMenu2.add(celsiusToKelvin);

        tempMenu.add(jMenu2);

        jMenu1.setText("Farhenheit");

        fahrenToCelsius.setText("Celsius");
        jMenu1.add(fahrenToCelsius);

        fahrenToKelvin.setText("Kelvin");
        jMenu1.add(fahrenToKelvin);

        tempMenu.add(jMenu1);

        kelvinToCelsius.setText("Kelvin");

        jMenuItem3.setText("Celsius");
        kelvinToCelsius.add(jMenuItem3);

        kelvinToFahren.setText("Farhenheit");
        kelvinToCelsius.add(kelvinToFahren);

        tempMenu.add(kelvinToCelsius);

        mainMenu.add(tempMenu);

        menuBar.add(mainMenu);

        blankMenuOption.setText("Edit");
        menuBar.add(blankMenuOption);

        setJMenuBar(menuBar);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(layout.createSequentialGroup()
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(divisionSign, javax.swing.GroupLayout.PREFERRED_SIZE, 57, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(subtractionSign, javax.swing.GroupLayout.PREFERRED_SIZE, 57, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(additionSign, javax.swing.GroupLayout.PREFERRED_SIZE, 57, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(multiplicationSign, javax.swing.GroupLayout.PREFERRED_SIZE, 57, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addGroup(layout.createSequentialGroup()
                                    .addComponent(numberZero, javax.swing.GroupLayout.PREFERRED_SIZE, 57, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(periodSign, javax.swing.GroupLayout.PREFERRED_SIZE, 57, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(equalsSign, javax.swing.GroupLayout.PREFERRED_SIZE, 57, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(layout.createSequentialGroup()
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                        .addComponent(numberSeven, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 57, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(numberOne, javax.swing.GroupLayout.PREFERRED_SIZE, 57, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(numberFour, javax.swing.GroupLayout.PREFERRED_SIZE, 57, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                                .addComponent(numberTwo, javax.swing.GroupLayout.PREFERRED_SIZE, 57, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addComponent(numberThree, javax.swing.GroupLayout.PREFERRED_SIZE, 57, javax.swing.GroupLayout.PREFERRED_SIZE))
                                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                                .addComponent(numberFive, javax.swing.GroupLayout.PREFERRED_SIZE, 57, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addComponent(numberSix, javax.swing.GroupLayout.PREFERRED_SIZE, 57, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                            .addComponent(numberEight, javax.swing.GroupLayout.PREFERRED_SIZE, 57, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                            .addComponent(numberNine, javax.swing.GroupLayout.PREFERRED_SIZE, 57, javax.swing.GroupLayout.PREFERRED_SIZE))))))
                        .addGroup(layout.createSequentialGroup()
                            .addComponent(blankBttn, javax.swing.GroupLayout.PREFERRED_SIZE, 57, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(squareRoot, javax.swing.GroupLayout.PREFERRED_SIZE, 57, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(clearText1, javax.swing.GroupLayout.PREFERRED_SIZE, 57, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(backSpace, javax.swing.GroupLayout.PREFERRED_SIZE, 57, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addComponent(textFeild, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 246, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(previousNumber, javax.swing.GroupLayout.PREFERRED_SIZE, 68, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(18, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addComponent(previousNumber, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(textFeild, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(blankBttn, javax.swing.GroupLayout.PREFERRED_SIZE, 59, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(squareRoot, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 59, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(backSpace, javax.swing.GroupLayout.PREFERRED_SIZE, 59, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(clearText1, javax.swing.GroupLayout.PREFERRED_SIZE, 59, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(additionSign, javax.swing.GroupLayout.PREFERRED_SIZE, 59, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(subtractionSign, javax.swing.GroupLayout.PREFERRED_SIZE, 59, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(multiplicationSign, javax.swing.GroupLayout.PREFERRED_SIZE, 59, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(divisionSign, javax.swing.GroupLayout.PREFERRED_SIZE, 59, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(numberNine, javax.swing.GroupLayout.PREFERRED_SIZE, 59, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(numberEight, javax.swing.GroupLayout.PREFERRED_SIZE, 59, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(numberSeven, javax.swing.GroupLayout.PREFERRED_SIZE, 59, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(numberFive, javax.swing.GroupLayout.PREFERRED_SIZE, 59, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(numberSix, javax.swing.GroupLayout.PREFERRED_SIZE, 59, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(numberFour, javax.swing.GroupLayout.PREFERRED_SIZE, 59, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(numberTwo, javax.swing.GroupLayout.PREFERRED_SIZE, 59, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(numberThree, javax.swing.GroupLayout.PREFERRED_SIZE, 59, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(numberOne, javax.swing.GroupLayout.PREFERRED_SIZE, 59, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(periodSign, javax.swing.GroupLayout.PREFERRED_SIZE, 59, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(numberZero, javax.swing.GroupLayout.PREFERRED_SIZE, 59, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(equalsSign, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 59, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    
    //Controls the switch statement which determines the operation to perform
    //it uses built in methods to parse the text into a double
    //Displays the result of the operations in the textfeild
    private void arithmetic_computations(){
        
        switch(calculations){
            case 0 -> {
                result = firstNumber + Double.parseDouble(textFeild.getText());
                textFeild.setText(Double.toString(result));
            }//Addition
            case 1 -> {
                result = firstNumber - Double.parseDouble(textFeild.getText());
                textFeild.setText(Double.toString(result));
            }//Subtraction
            case 2 -> {
                result = firstNumber * Double.parseDouble(textFeild.getText());
                textFeild.setText(Double.toString(result));
            }//Multiplication
            case 3 -> {
                result = firstNumber / Double.parseDouble(textFeild.getText());
                textFeild.setText(Double.toString(result));
            }//Division
            case 4 -> {
                result = Math.pow(firstNumber, 2);
                textFeild.setText(Double.toString(result));
            }//Squared
                
        }
    
    }
    
    
    //Sets the textFeild to the applicable number
    private void numberEightActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_numberEightActionPerformed
         textFeild.setText(textFeild.getText() + "8");
    }//GEN-LAST:event_numberEightActionPerformed

    private void numberZeroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_numberZeroActionPerformed
        textFeild.setText(textFeild.getText() +  "0");
    }//GEN-LAST:event_numberZeroActionPerformed

    private void numberOneActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_numberOneActionPerformed
         textFeild.setText(textFeild.getText() +  "1");
    }//GEN-LAST:event_numberOneActionPerformed

    private void numberTwoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_numberTwoActionPerformed
         textFeild.setText(textFeild.getText() +  "2");
    }//GEN-LAST:event_numberTwoActionPerformed

    private void numberThreeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_numberThreeActionPerformed
         textFeild.setText(textFeild.getText() +  "3");
    }//GEN-LAST:event_numberThreeActionPerformed

    private void numberSixActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_numberSixActionPerformed
         textFeild.setText(textFeild.getText() +  "6");
    }//GEN-LAST:event_numberSixActionPerformed

    private void numberFourActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_numberFourActionPerformed
         textFeild.setText(textFeild.getText() +  "4");
    }//GEN-LAST:event_numberFourActionPerformed

    private void numberFiveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_numberFiveActionPerformed
         textFeild.setText(textFeild.getText() +  "5");
    }//GEN-LAST:event_numberFiveActionPerformed

    private void numberSevenActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_numberSevenActionPerformed
         textFeild.setText(textFeild.getText() +  "7");
    }//GEN-LAST:event_numberSevenActionPerformed

    private void numberNineActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_numberNineActionPerformed
         textFeild.setText(textFeild.getText() +  "9");
    }//GEN-LAST:event_numberNineActionPerformed

    
    //Sets the firstNumber equal to the amount currently displayed in the textFeild
    //Sets calculation to the operations' switch and the text feild to null
    //sets the text feild at the top equal to the firstNumber + the operation sign
    private void squareRootActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_squareRootActionPerformed
        firstNumber = Double.parseDouble(textFeild.getText());
        calculations = 4;
        textFeild.setText("");
        previousNumber.setText(firstNumber + " ^2 ");
    }//GEN-LAST:event_squareRootActionPerformed

    private void additionSignActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_additionSignActionPerformed
        firstNumber = Double.parseDouble(textFeild.getText());
        calculations = 0;
        textFeild.setText("");
        previousNumber.setText(firstNumber + " + ");
        
    }//GEN-LAST:event_additionSignActionPerformed

    private void subtractionSignActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_subtractionSignActionPerformed
        firstNumber = Double.parseDouble(textFeild.getText());
        calculations = 1;
        textFeild.setText("");
        previousNumber.setText(firstNumber + " - ");
    }//GEN-LAST:event_subtractionSignActionPerformed

    private void multiplicationSignActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_multiplicationSignActionPerformed
        firstNumber = Double.parseDouble(textFeild.getText());
        calculations = 2;
        textFeild.setText("");
        previousNumber.setText(firstNumber + " * ");
    }//GEN-LAST:event_multiplicationSignActionPerformed

    private void divisionSignActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_divisionSignActionPerformed
        firstNumber = Double.parseDouble(textFeild.getText());
        calculations = 3;
        textFeild.setText("");
        previousNumber.setText(firstNumber + " / ");
    }//GEN-LAST:event_divisionSignActionPerformed

    
    
    private void backSpaceActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backSpaceActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_backSpaceActionPerformed

    private void clearText1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_clearText1ActionPerformed
        textFeild.setText("");
    }//GEN-LAST:event_clearText1ActionPerformed

    private void equalsSignActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_equalsSignActionPerformed
        arithmetic_computations();
        previousNumber.setText("");
    }//GEN-LAST:event_equalsSignActionPerformed

    private void blankBttnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_blankBttnActionPerformed
        textFeild.setText(null);
    }//GEN-LAST:event_blankBttnActionPerformed

    private void textFeildActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_textFeildActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_textFeildActionPerformed

    private void simpleInterestActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_simpleInterestActionPerformed
            
        
        
        
        if(textFeild.getText().isEmpty()){
            previousNumber.setText("Principle Amount");
        }
        
    
              String principleString = textFeild.getText();
              principleAmount = Double.parseDouble(principleString);
          
         
          
//        
//        textFeild.setText("Rate: ");
//        rate = Double.parseDouble(textFeild.getText());
//        
//        textFeild.setText("Time Span: ");
//        timeSpan = Double.parseDouble(textFeild.getText());
//        
//        
//        
//        Interest house = new Interest(principleAmount, rate, timeSpan);
    }//GEN-LAST:event_simpleInterestActionPerformed

    private void celsiusToFahrenheitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_celsiusToFahrenheitActionPerformed
        currentType = 0;
        desiredType = 1;
        textFeild.setText(null);
        
        while(textFeild.getText().isEmpty()){
            previousNumber.setText("Temp: ");
            
            
            if(!textFeild.getText().isEmpty()){
                temp = Double.parseDouble(scnr.next(textFeild.getText()));            
            }
        }
            
        
        
        TempConverter newConversion = new TempConverter(currentType, desiredType, temp);
    }//GEN-LAST:event_celsiusToFahrenheitActionPerformed

    private void previousNumberActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_previousNumberActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_previousNumberActionPerformed


    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton additionSign;
    private javax.swing.JButton backSpace;
    private javax.swing.JButton blankBttn;
    private javax.swing.JMenu blankMenuOption;
    private javax.swing.JMenuItem celsiusToFahrenheit;
    private javax.swing.JMenuItem celsiusToKelvin;
    private javax.swing.JButton clearText1;
    private javax.swing.JMenuItem compoundInterest;
    private javax.swing.JButton divisionSign;
    private javax.swing.JButton equalsSign;
    private javax.swing.JMenuItem fahrenToCelsius;
    private javax.swing.JMenuItem fahrenToKelvin;
    private javax.swing.JMenu interestMenu;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenuItem jMenuItem3;
    private javax.swing.JMenu kelvinToCelsius;
    private javax.swing.JMenuItem kelvinToFahren;
    private javax.swing.JMenuItem lossCalculation;
    private javax.swing.JMenu mainMenu;
    private javax.swing.JMenuBar menuBar;
    private javax.swing.JButton multiplicationSign;
    private javax.swing.JButton numberEight;
    private javax.swing.JButton numberFive;
    private javax.swing.JButton numberFour;
    private javax.swing.JButton numberNine;
    private javax.swing.JButton numberOne;
    private javax.swing.JButton numberSeven;
    private javax.swing.JButton numberSix;
    private javax.swing.JButton numberThree;
    private javax.swing.JButton numberTwo;
    private javax.swing.JButton numberZero;
    private javax.swing.JButton periodSign;
    private javax.swing.JTextField previousNumber;
    private javax.swing.JMenuItem profitCalculation;
    private javax.swing.JMenu profitMenu;
    private javax.swing.JMenuItem simpleInterest;
    private javax.swing.JButton squareRoot;
    private javax.swing.JButton subtractionSign;
    private javax.swing.JMenu tempMenu;
    private javax.swing.JTextField textFeild;
    // End of variables declaration//GEN-END:variables
}
